[package]
name = "ffblame"
version = "0.1.0"
edition = "2021"

[dependencies]
openff-toolkit = { path = "../../../omsf/rust/coprelos/openff-toolkit" }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
